{%- set MANAGER = salt['pillar.get']('global:managerip', '') %}
apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    url: https://{{ MANAGER }}:8086
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
    version: 1
